(function(root){
'use strict';
const SPORTS=['Football','Rugby','Handball','Basket','Tennis','Athlétisme','Multisport'];
const TYPES={article:'Actualité',event:'Événement',result:'Résultat',club:'Club'};
const KEY='aix-sport-local-v1';
function escape(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function validURL(s){if(!s)return '';try{let u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}}
function validate(x){if(!x||typeof x!=='object'||Array.isArray(x))throw Error('Contenu invalide.');if(!Object.keys(TYPES).includes(x.type))throw Error('Choisis un type de contenu.');if(!SPORTS.includes(x.sport))throw Error('Choisis un sport.');if(!String(x.title||'').trim())throw Error('Ajoute un titre.');if(!String(x.body||'').trim())throw Error('Ajoute un texte.');if(x.type==='event'&&!x.date)throw Error('Ajoute la date de l’événement.');if(x.source&&!validURL(x.source))throw Error('Le lien doit commencer par http:// ou https://.');if(x.date&&(!/^\d{4}-\d{2}-\d{2}$/.test(x.date)||new Date(x.date+'T12:00:00').toISOString().slice(0,10)!==x.date))throw Error('Date invalide.');if(x.image&&!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(x.image))throw Error('Image invalide.');if(x.image&&x.image.length>1500000)throw Error('Image trop volumineuse.');for(const k of ['title','club','venue','score'])if(String(x[k]||'').length>200)throw Error('Un champ court dépasse 200 caractères.');if(String(x.body).length>30000)throw Error('Texte trop long (30 000 caractères maximum).');return {id:String(x.id||crypto.randomUUID()),type:x.type,sport:x.sport,title:String(x.title).trim(),body:String(x.body).trim(),club:String(x.club||''),venue:String(x.venue||''),score:String(x.score||''),date:String(x.date||''),source:validURL(x.source),image:x.image||'',status:x.status==='published'?'published':'draft',demo:x.demo===true,updated:x.updated||new Date().toISOString()};}
function parseBackup(raw){let data=JSON.parse(raw);if(data.version!==1||!Array.isArray(data.items)||data.items.length>500)throw Error('Ce fichier n’est pas une sauvegarde compatible (maximum 500 contenus).');let items=data.items.map(validate);if(new Set(items.map(x=>x.id)).size!==items.length)throw Error('La sauvegarde contient des identifiants en double.');return items;}
const demo=[['Rugby','La vie de votre club, au plus près du terrain','Présentez ici votre club, son équipe et les personnes qui le font vivre. Remplacez cet exemple par votre première actualité.'],['Handball','Les rendez-vous sportifs à ne pas manquer','Annoncez ici une rencontre, un tournoi ou une journée découverte. Ajoutez vos propres dates et informations vérifiées.'],['Multisport','Un club, une équipe, une histoire à raconter','Mettez en lumière les bénévoles, les sportifs et les initiatives du Pays d’Aix. Ce texte est un exemple à personnaliser.']].map((x,i)=>({id:'exemple-'+i,type:'article',sport:x[0],title:x[1],body:x[2],club:'',venue:'',score:'',date:'',source:'',image:'',status:'published',demo:true,updated:'2026-01-01T00:00:00Z'}));
root.AixCore={SPORTS,TYPES,KEY,escape,validURL,validate,parseBackup,demo};if(typeof module!=='undefined')module.exports=root.AixCore;
})(typeof window!=='undefined'?window:globalThis);
