const {test}=require('node:test');const assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');const {once}=require('node:events');const {MongoClient}=require('mongodb');const {createAuth,tokenHash}=require('../auth.cjs');const {createServer}=require('../server.cjs');
test('GitHub Pages vers Render : sessions sans cookies tiers et isolation',async t=>{
 const c=new MongoClient(process.env.TEST_MONGODB_URI||'mongodb://127.0.0.1:27017',{serverSelectionTimeoutMS:5000});const name='sportsensemble_test_cors_'+randomUUID().replaceAll('-','');let server;await c.connect();const db=c.db(name);const origin='https://api.example.invalid',front='https://nahelsamson.github.io';
 t.after(async()=>{if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}if(/^sportsensemble_test_cors_[a-f0-9]{32}$/.test(name))await db.dropDatabase();await c.close();});
 let healthy=true;server=createServer(await createAuth(db,{origin,secureCookie:true,tokenOrigins:[front,'https://second.example.invalid']}),{healthCheck:()=>{if(!healthy)throw Error('private database detail');}});server.listen(0,'127.0.0.1');await once(server,'listening');const base='http://127.0.0.1:'+server.address().port;
 async function req(endpoint,{body,token,requestOrigin=front,mode=true,cookie,method}={}){const r=await fetch(base+'/api/auth/'+endpoint,{method:method||(body===undefined?'GET':'POST'),headers:{...(requestOrigin?{Origin:requestOrigin}:{}),...(mode?{'X-Session-Mode':'token'}:{}),...(body!==undefined?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{}),...(cookie?{Cookie:cookie}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});return {r,body:await r.json()};}
 const preflight=await fetch(base+'/api/auth/login',{method:'OPTIONS',headers:{Origin:front,'Access-Control-Request-Method':'POST','Access-Control-Request-Headers':'content-type,x-session-mode,authorization'}});assert.equal(preflight.status,204);assert.equal(preflight.headers.get('access-control-allow-origin'),front);assert.equal(preflight.headers.get('access-control-allow-credentials'),null);
 const untrusted=await req('me',{requestOrigin:'https://evil.invalid'});assert.equal(untrusted.r.status,403);assert.equal(untrusted.r.headers.get('access-control-allow-origin'),null);
 assert.equal((await req('me',{mode:false})).r.status,403);assert.equal((await req('me',{requestOrigin:null})).r.status,403);
 const account={name:'Compte distant',email:'cors@example.invalid',password:'Verification des comptes distant 2026!'};const registered=await req('register',{body:account});assert.equal(registered.r.status,201);assert.equal(registered.r.headers.get('set-cookie'),null);assert.equal(registered.r.headers.get('access-control-allow-origin'),front);const token=registered.body.sessionToken;assert.match(token,/^[a-f0-9]{64}$/);const session=await db.collection('sessions').findOne({tokenHash:tokenHash(token)});assert.equal(session.audience,front);assert.equal(session.token,undefined);
 assert.equal((await req('me',{token})).body.user.id,registered.body.user.id);assert.equal((await req('me',{token,requestOrigin:'https://second.example.invalid'})).body.user,null);assert.equal((await req('me',{mode:false,requestOrigin:origin,cookie:'sportsensemble_session='+token})).body.user,null);
 const agenda={age:22,sports:['Arts martiaux'],selectedIds:['aix-01-007']};assert.equal((await req('agenda',{token,body:agenda})).r.status,200);const slot={id:'render-session',clubId:'aix-01-007',day:1,start:1080,end:1140,source:'proposal',proposalKey:'1-1080-1140'};assert.equal((await req('week',{token,body:{revision:0,sessions:[slot]}})).r.status,200);assert.deepEqual((await req('me',{token})).body.user.weeklyPlan.sessions,[slot]);
 const second=await req('register',{body:{...account,email:'second-cors@example.invalid'}});assert.equal((await req('me',{token:second.body.sessionToken})).body.user.agenda,null);
 assert.equal((await req('logout',{token,body:{}})).r.status,200);assert.equal((await req('me',{token})).body.user,null);const login=await req('login',{body:account});assert.equal(login.r.status,200);assert.deepEqual(login.body.user.agenda,agenda);
 const cookieLogin=await req('login',{body:account,mode:false,requestOrigin:origin});assert.match(cookieLogin.r.headers.get('set-cookie'),/Secure/);assert.equal(cookieLogin.body.sessionToken,undefined);const cookieToken=cookieLogin.r.headers.get('set-cookie').split(';')[0].split('=')[1];assert.equal((await req('me',{token:cookieToken})).body.user,null);
 await db.collection('sessions').updateOne({tokenHash:tokenHash(login.body.sessionToken)},{$set:{expiresAt:new Date(0)}});assert.equal((await req('me',{token:login.body.sessionToken})).body.user,null);
 assert.deepEqual(await (await fetch(base+'/healthz')).json(),{ok:true});healthy=false;const unavailable=await fetch(base+'/healthz');assert.equal(unavailable.status,503);assert.deepEqual(await unavailable.json(),{ok:false});
 for(const file of ['/.env','/render.yaml','/.private/site-domain.json'])assert.equal((await fetch(base+file)).status,404);
});
